Added subscription types meta CRD form and move to widget
remp2020/crm-subscriptions-module pull request #4
Opened 2020-03-31 16:06 UTC by ricco24

Added form for create and delete subscription types meta in subscription type show screen.
Moved subscription types meta to widget.

2020-04-01 20:07 UTC, rootpd requested changes
Feature-wise it works great, UI-wise I'd like to make it more consistent with the rest of the form. Two blocks below there's subscription items block to manage `subscription_type_items`.

It more-or-less works the same way. There are some items, you can add them, remove them and you want to validate the input.

* The main difference is that the form for adding is in the modal and not visible by default.
* Second is the bootstrap elements used to render the block

Could you align this implementation with the one used in subscription type items?

![subscription_type_items](https://user-images.githubusercontent.com/812909/78181654-0e615480-7465-11ea-9915-eb74ecb6a399.gif)

2020-04-01 20:07 UTC, rootpd commented on src/models/Repository/SubscriptionTypesMetaRepository.php
> +        return $this->getTable()->where(['subscription_type_id' => $subscriptionType['id']])->order('key ASC');
I wouldn't probably omit forced `order` on the repository level - it's not possible to change it in case someone wants to use other ordering. Unless the order is logical (some `sorting` column that should enforce ordering), it's better to let component/presenter state the `order`.

2020-04-02 09:31 UTC, ricco24 commented on src/models/Repository/SubscriptionTypesMetaRepository.php
> +        return $this->getTable()->where(['subscription_type_id' => $subscriptionType['id']])->order('key ASC');
Yes, you have right.

2020-04-02 09:32 UTC, ricco24 commented
UI changed

2020-04-02 09:35 UTC, ricco24 commented
But unfortunately it is impossible to make component registered via simpleWidget ajax-like. AFAIK components with snippets needs to have "stupid" render() method without parameters. Because in invalidation process is called only ->render() on all components.

2020-04-02 11:54 UTC, rootpd commented
@ricco24 That's right. Dump the widget, render it directly to the view as subscription type items are being rendered. Separating it to widget is no longer worth it due to the limitations.

2020-04-21 15:20 UTC, ricco24 commented
@rootpd GUI updated

2020-04-21 15:56 UTC, ricco24 commented
Everything updated to ajax

2020-04-30 05:00 UTC, ricco24 commented
@rootpd hi, can you look at this please?

2020-04-30 06:49 UTC, rootpd commented
Sorry, will do. The amount of PRs is higher at this moment and we're struggling a bit with the review speed :).

2020-05-05 12:28 UTC, rootpd commented
Looks good. I did some cleanup internally and put it on internal review before we merge it. ETA tomorrow.

2020-05-06 07:33 UTC, rootpd commented
You've been merged :). https://github.com/remp2020/crm-subscriptions-module/commit/0c8a12b28c87d78c14bc08a31a411b183d490540

2020-05-06 07:33 UTC, closed without merging